# fly.toml app configuration file generated for chromawalk2 on 2026-05-07T00:03:47+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chromawalk2'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
